#!/usr/bin/env bash

spaces (){
	# WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
	WORKSPACE_WINDOWS=$(swaymsg --raw -t get_tree | jq ".nodes[1].nodes | map({key:.name, value: (.nodes|length)}) | from_entries")
	seq 1 5 | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
}

spaces
swaymsg --raw -m -t SUBSCRIBE '["workspace", "window"]' | while read -r line; do
# socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	spaces
done
