#!/bin/sh

brightnessctl -e1.5 -d chromeos::kbd_backlight -m info | awk -F ',' '{print $4}' | sed 's/%//g'
while inotifywait -e modify /sys/class/leds/chromeos::kbd_backlight/brightness 2>/dev/null >/dev/null;
do
	brightnessctl -e1.5 -d chromeos::kbd_backlight -m info | awk -F ',' '{print $4}' | sed 's/%//g'
done
